### ISSUE TITLE
nextcloud-initial-state can't be used in Settings

### ISSUE THREAD

**Issue by StCyr** [nextcloud-libraries/nextcloud-initial-state#230]
From what I understand, nextcloud-initial-state can't be used in Settings which makes it unsuitable to replace OCP.AppConfig

**Comment by susnux** [comment]
It does work, for example see the current logreader implementation:

https://github.com/nextcloud/logreader/blob/48cd00164a4eccbfb5d088e57951705c596753eb/src/store/settings.ts#L27

https://github.com/nextcloud/logreader/blob/48cd00164a4eccbfb5d088e57951705c596753eb/lib/Settings/Admin.php#L47
